### ISSUE TITLE
Webpack uglify build breaks

### ISSUE THREAD

**Issue by cyrus-za** [sindresorhus/gravatar-url#1]
When I run a build command with my next.js project the build fails with this error: 

```{ Error: commons.js from UglifyJs
Invalid assignment [commons.js:33718,31]
...
}
```

I checked in my build directory what that line resolves to and saw that it's this `gravatar-url` package. 

```javascript
33716 const BASE_URL = 'https://gravatar.com/avatar/';
33717
33718 module.exports = (email, opts) => {
33719    if (email.indexOf('@') === -1) {
33720        throw new Error('Please specify an email');
33721    }
33722
33723    const query = querystring.stringify(opts);
33724
33725    return BASE_URL + md5Hex(email.toLowerCase().trim()) + (query ? `?${query}` : '');
33726};

```

See how line 33718 has an arrow function. I do use babel to transpile es6 to es5 which works for all other modules, but somehow this one is stuck in es6. 

This could very well be a issue in my own config, but I figured I'd log the issue here in case anyone else struggles with this.

I solved it by switching from `gravatar-url` to `gravatar` package

**Comment by kevva** [comment]
Are you sure it's transpiled? Doesn't look like it.

**Comment by sindresorhus** [comment]
> This could very well be a issue in my own config

Yes

**Comment by EdwardSalter** [comment]
I have just come across the same issue and by taking a quick look at the code I believe it stems from the use of string interpolation.
I believe that UglifyJS runs solely on ES5 code so the string interpolation trips it up.
