### ISSUE TITLE
React  Build Fails to minify code from the module.

### ISSUE THREAD

**Issue by ghost** [sindresorhus/gravatar-url#2]
I get the error below when I run yarn build. followed the link http://bit.ly/2tRViJ9. Please check this out.
```
Failed to compile.

Failed to minify the code from this file: 

 	./node_modules/gravatar-url/index.js:7 

Read more here: http://bit.ly/2tRViJ9

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by sindresorhus** [comment]
This module mainly targets Node.js, not the browser. It's up to you to transpile it with Babel if you want to use it in the browser. You can find a more detailed explanation here: https://github.com/sindresorhus/ama/issues/446

I'm sorry that `create-react-app` is lacking in this aspect, but it's up to them to support the community. Each package should not be required to specially support `create-react-app`. Please do open an issue on `create-react-app` about this pain point.
