### ISSUE TITLE
Don't check for @ in email address

### ISSUE THREAD

**Issue by thomas-darling** [sindresorhus/gravatar-url#6]
The current implementation checks whether the specified email contains an `@`.
While that technically makes sense, it is an unnecessary constraint that actually gets in the way.

**Example:**
We're building an app that has a collection of projects, where users may associate a "profile picture" with each project, to make it easier to recognize. However, as an alternative to uploading a picture, we offer users the option to use a Gravatar instead - which is generated not based on an email, but based on the ID of the project.

When generating the Gravatar URL, we currently have to prefix our project ID with an `@` to make `gravatar-url` happy - but wouldn't it make sense to just drop this unnecessary constraint?
Gravatar only see the hash anyway...

**Comment by sindresorhus** [comment]
I never thought of the use-case of using Gravatar to get a pseudo-random avatar based on any kind of hash. That's a cool use-case. Happy to lift the restriction if you can also document this use-case in the readme as I think many others are under the assumption it has to be a valid email, not just any kind of hash.

**Comment by thomas-darling** [comment]
I've created a couple of pull requests - feel free to comment :-)
