### ISSUE TITLE
Parcel failing with "Unknown pipeline: node" error

### ISSUE THREAD

**Issue by broofa** [sindresorhus/gravatar-url#8]
I'm trying to pull this into a project that uses `parcel` to bundle everything.  Parcel is choking with the following error:

```
@parcel/core: Unknown pipeline: node.
/Users/kieffer/projects/flightcard/node_modules/gravatar-url/index.js:1:25
> 1 | import querystring from 'node:querystring';
>   |                         ^^^^^^^^^^^^^^^^^^
  2 | import md5Hex from 'md5-hex';
  3 |
```

BTW, I haven't seen an import incantation like `node:querystring` before... what is that expected to do?

**Comment by broofa** [comment]
Would it make sense to use `URLSearchParams` here instead?

**Comment by sindresorhus** [comment]
> BTW, I haven't seen an import incantation like node:querystring before... what is that expected to do?

This is a Parcel issue. `node:querystring` is a perfectly valid import.

**Comment by sindresorhus** [comment]
> Would it make sense to use URLSearchParams here instead?

Yes

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/gravatar-url/releases/tag/v4.0.1
